import { Inter } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'
const pop = localFont({src:"../fonts/Poppins-Medium.ttf"})
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bitsniper',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className} style={pop.style}>{children}</body>
    </html>
  )
}
